sudo: required

services:
  - docker

env:
  global:
    - VERSION=1.13.3
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=csgo-server-launcher
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=csgo-server-launcher
    - secure: a5WY8nZ2hw/yi7GavfkDmO4VzXg0InNyHy1tVK4ZZj5ATnW6foHAHnZUXHjavqUTOTWZlayYLihZ8/9KZ/vz319SHihCLVF6L2lCpdM0+xVp9zqAfN+TcJuMoGiBZczcMzNPjG8c/XqcQMTN0EEg9PaxsbcA2gayvYBS2Hj+kA4= # DOCKER_PASSWORD
    - secure: E+gDZoEf5Pn6MV4Oorxoaa4WXh0b+kPK35AqV3QMOxG2b4S7l/lW4HY59W8S7xv6CDdUC4LPjoQp1VEH6EWbJ3EJgSDFWgAZMeYD+gHSNvAu6OJAryDpZSpXxyED7BNNf8AqAr2PYhHM7VtBLErVwDQYbt7I8CVOmofsAFhSOYc= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

script: ./build.sh

notifications:
  email:
    recipients:
      - travisci@crazymax.dev
    on_success: always
    on_failure: always
